development:
  adapter: postgresql
  encoding: unicode
  database: groupgames-development
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: groupgames-production